baseURL = "https://alon.com.np"
title = "Alon Shrestha"
paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-EKGRJ57WET"
pygmentsUseClasses = true
publishDir = "docs"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "asdasd"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Alon Shrestha"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "/images/favicon/favicon.ico"
favicon16x16 = "/images/favicon/favicon-16x16.png"
favicon32x32 = "/images/favicon/favicon-32x32.png"
apple_touch_icon = "/images/favicon/apple-touch-icon.png"
safari_pinned_tab = "/images/favicon/safari-pinned-tab.svg"
disableFingerprinting = true

[params.label]
text = "@alonshrestha"
icon = "/images/homepage/alondp.jpg"
iconHeight = 45

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
    name = "Blogs"
    url = "blogs"

[[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

[params.homeInfoParams]
Title = "[~] $ whoami"
Content = """
[üëã Hi, I'm Alon!](#) With a background in Computer Science, I'm passionate about ‚òÅÔ∏è Cloud, üîí Security, üõ†Ô∏è DevOps, and ü§ñ Automation - you guessed it - orchestrating the whole infrastructure. Apart from tech, I love doing music üé∏, travelling ‚õ∞Ô∏è and sometimes fitness üèãÔ∏è‚Äç‚ôÇÔ∏è. Lately, I've developed a passion for writing, leading to the birth of this website (still a work-in-progress). [Curious for more](/about) or up for a chat? Drop me a line at alonshstha@gmail.com.
"""
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[params.analytics.google]
SiteVerificationTag = "G-EKGRJ57WET"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = false
hiddenInSingle = false


[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "topics"
name = "Topics"
url = "/topics/"
weight = 2

[[menu.main]]
identifier = "blogs"
name = "Blogs"
url = "/blogs/"
weight = 3

[[menu.main]]
identifier = "Reume"
name = "My Resume"
url = "https://alonshrestha.com.np"
weight = 4

[markup.highlight]
noClasses = false

[taxonomies]
topic = "topics"